language: javascript
node_js:
  - 10

install:
  - npm install --global @vue/cli@3.4.1 @vue/cli-init@3.4.1
  - npm install --global @quasar/cli@1.0.0-beta.3
  - npm install
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  target_branch: master
  keep-history: true
  on:
    branch: master

script: ./quasar.build.sh
