language: node_js
node_js:
  - "10"

cache:
  npm: true

install:
  - npm install --global @vue/cli@3.4.1 @quasar/cli@1.0.0-beta.3
  - yarn install

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm test; fi'

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./.travis.deploy.sh; fi'

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  verbose: true
  on:
    master: true
    tags: true
