language: javascript
node_js:
  - 10
cache:
  yarn: true
  npm: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - npm install --global @vue/cli@3.4.1 @vue/cli-init@3.4.1
  - npm install --global @quasar/cli@1.0.0-beta.3
  - yarn install

script:
  - quasar build -m spa
  - rm -rf ./docs/*
  - cp -R ./dist/spa/* ./docs

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  target_branch: master
  keep-history: true
  on:
    branch: master
