language: node_js
node_js:
  - "10"
cache:
  npm: true
  directories:
    - $TRAVIS_BUILD_DIR

install:
  - npm install --global @vue/cli@3.4.1 @vue/cli-init@3.4.1
  - npm install --global @quasar/cli@1.0.0-beta.3
  - cd $TRAVIS_BUILD_DIR
  - npm install

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash $TRAVIS_BUILD_DIR/.travis.sh; fi'

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  target_branch: master
  keep-history: true
  on:
    branch: master
